language: go
sudo: false
jobs:
  include:
    - stage: build
      os: osx
      go: 1.12.x
      script:
        - sh build.sh all

    - stage: build
      os: linux
      go: 1.12.x
      script:
        - sh build.sh all